# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1vGANHw3lCKtKAnQjeRH7EFSLAVhzH3
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

import sqlite3

# Connect to the database (creates file if it doesn't exist)
conn = sqlite3.connect("sales_data.db")
cursor = conn.cursor()

# Create the sales table
cursor.execute("DROP TABLE IF EXISTS sales")  # optional: delete old table
cursor.execute("""
    CREATE TABLE sales (
        id INTEGER PRIMARY KEY,
        product TEXT,
        quantity INTEGER,
        price REAL
    )
""")

# Insert sample data
sample_data = [
    ('Apples', 10, 0.5),
    ('Bananas', 15, 0.3),
    ('Oranges', 20, 0.7),
    ('Apples', 5, 0.5),
    ('Bananas', 10, 0.3),
    ('Oranges', 5, 0.7)
]
cursor.executemany("INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)", sample_data)

# Save changes
conn.commit()

import pandas as pd

# SQL query to summarize data
query = """
    SELECT
        product,
        SUM(quantity) AS total_qty,
        SUM(quantity * price) AS revenue
    FROM sales
    GROUP BY product
"""

# Load into a DataFrame
df = pd.read_sql_query(query, conn)

# Print the result
print("Sales Summary:")
print(df)

import matplotlib.pyplot as plt

# Plot revenue by product
df.plot(kind='bar', x='product', y='revenue', legend=False, color='skyblue')
plt.title("Revenue by Product")
plt.ylabel("Revenue ($)")
plt.tight_layout()

# Optional: Save chart as image
plt.savefig("sales_chart.png")

# Show the chart
plt.show()

conn.close()

import os
os.listdir()

files.download('sales_data.db')

files.download('sales_chart.png')